Add First Version of Repolinter Action
DSACMS/metrics pull request #123
Opened 2024-04-11 19:30 UTC by IsaacMilarky

## Add First Version of Repolinter Action

## Problem

Repolinter is not currently run automatically as a check GH action. 

## Solution

Use [repolinter-action](https://github.com/newrelic/repolinter-action) to run repolinter as an action. This action is using the tier 3 repolinter.json that was created. This is because if I remember correctly Metrics is a tier 3 project.

The action will create an issue on the project to give remediation steps to follow tier 3 project requirements.

2024-04-11 19:35 UTC, IsaacMilarky commented
There seems to be some problems with the format of the `repolinter.json` file. I will look into this but shouldn't merge in the meantime. 

```
 Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: A fatal error was thrown.
Error: Error: Configuration validation failed with error Configuration validation failed with errors: 
	configuration.rules['maintainers-file-exists'] should have required property 'rule'
    at Object.rejected (/repolinter-action/webpack:/repolinter-action/lib/getConfig.js:109:1)
    at Generator.next (<anonymous>)
    at fulfilled (/repolinter-action/webpack:/repolinter-action/lib/getConfig.js:25:1)
```

2024-04-12 22:12 UTC, IsaacMilarky commented
Ready to merge now.

2024-04-12 22:45 UTC, natalialuzuriaga requested changes
Since we are unable to extend from the Tier 2 repolinter.json file, I noted a couple of checks whose levels need to be changed to match Tier 3 requirements

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "warning",
level should be "error"

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "warning",
level should be "error"

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "off",
level should be "warning"

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "off",
level should be "error"

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "off",
level should be "error"

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "off",
level should be "error"

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "off",
level should be "error"

2024-04-12 22:45 UTC, natalialuzuriaga commented on repolinter.json
> +			"level": "off",
level should be "error"

2024-04-12 23:18 UTC, IsaacMilarky commented
> Since we are unable to extend from the Tier 2 repolinter.json file, I noted a couple of checks whose levels need to be changed to match Tier 3 requirements

Oh my bad I forgot to merge the Tier 3 changes into the JSON. Will fix

2024-04-16 22:08 UTC, natalialuzuriaga approved these changes
LGTM! ✅

2024-04-16 23:22 UTC, merged