Add code.json File with Repometrics
DSACMS/metrics pull request #177
Opened 2024-07-10 22:29 UTC by RicardoZamora01

## module-name: Add code.json File with Repometrics

## Problem

We currently do not have repo metrics for this project to be added in the project report.

## Solution

Added code.json file with repometrics fields.

2024-07-11 17:46 UTC, natalialuzuriaga requested changes

2024-07-11 17:46 UTC, natalialuzuriaga commented on code.json
> +    "group": "DSAC",
Same comment as [DedupliFHIR PRI](https://github.com/DSACMS/dedupliFHIR/pull/73)

2024-07-11 18:20 UTC, IsaacMilarky approved these changes

2024-07-12 16:10 UTC, natalialuzuriaga approved these changes

2024-07-12 18:32 UTC, merged