Add Metric to Gather Badge URL for Nadia Asparouhova's Project Types
DSACMS/metrics pull request #98
Opened 2024-03-28 15:55 UTC by IsaacMilarky

## Add Metric to Gather Badge URL for Nadia Asparouhova's Project Types

## Problem

We are not utilizing the upstream Augur Nadia categorization endpoint as well as the shield badging endpoint in order to show a badge on our metrics repo report page. 

## Solution

I have added a new CustomMetric to accomplish this task. The metric hits the augur endpoint to retrieve the category the repository belongs to and then plugs the resulting arguments into a url to generate a badge from a shields endpoint. Here is an example: https://img.shields.io/static/v1?label=project+type&message=Midsize&color=red.

## Result

In order for this badge to display we should embed the svg tag found in the resulting recorded shield url. 

Here are what the badges look like:

![project_type_Midsize](https://github.com/DSACMS/metrics/assets/24639268/f48c96bc-4bb0-4d53-8e18-6534dbed5953)
![project type club](https://github.com/DSACMS/metrics/assets/24639268/3bfd58f9-4015-4938-a003-28b7ea76c537)
![project type toy](https://github.com/DSACMS/metrics/assets/24639268/8b0e6c08-27c6-4c9b-a4cb-742aa8cd2b42)
![project type stadium](https://github.com/DSACMS/metrics/assets/24639268/1ccd9064-862b-4ef1-9ba3-799816e0d99f)
![project type federation](https://github.com/DSACMS/metrics/assets/24639268/ce8cde3b-f8c8-4601-9822-9fc9bedd6b59)

2024-04-05 18:09 UTC, IsaacMilarky commented
This addresses Issue #8

2024-04-08 18:29 UTC, natalialuzuriaga reviewed
LGTM! I changed the location of the badge so it's under the title. There's a lot of spacing between the letters though... going to see if I can do some adjustments

<img width="744" alt="Screenshot 2024-04-08 at 11 03 55 AM" src="https://github.com/DSACMS/metrics/assets/29980737/56bb9234-8047-472a-80e3-df140183bdef">
<img width="711" alt="Screenshot 2024-04-08 at 11 27 25 AM" src="https://github.com/DSACMS/metrics/assets/29980737/283320a8-35f3-4f92-9ae1-373678348b0f">

2024-04-08 22:06 UTC, natalialuzuriaga requested changes
Alright, I was able to make the adjustments with the text configs! Just a couple of minor tweaks need to be made with the nadia label variables in the metrics data and this is good to go!

2024-04-08 22:06 UTC, natalialuzuriaga commented on app/site/_includes/project-type-tag.liquid
> +  {% when "midsize" %}
nit: for consistency, could you make "midsize" all lowercase in the metrics data for the field `nadia_badge_name`?

2024-04-08 22:06 UTC, natalialuzuriaga commented on app/site/_includes/project-type-tag.liquid
> +    <img src="{{ link }}" alt="Project Type"/>
For `nadia_shields_badge_url` in the metrics data, can you remove the "#" from the color param? It isn't setting the color accordingly because of it

2024-04-08 22:20 UTC, IsaacMilarky commented
> Alright, I was able to make the adjustments with the text configs! Just a couple of minor tweaks need to be made with the nadia label variables in the metrics data and this is good to go!

Made the requested changes. Let me know if it all looks good to merge!

2024-04-08 22:23 UTC, natalialuzuriaga approved these changes
Perfect, LGTM ✅

2024-04-08 22:38 UTC, merged

2024-04-10 17:31 UTC, decause-gov reviewed
🚢